---
  # Private key file that we will distribute to our newly created
  # machines
  userPrivateKeyFile: ~/.ssh/do-default-key_rsa
  # User that we will set up on the machine
  userName: "chr"
  # Name of the key that is on file with the cloud provider and
  # that we will use for the initial access
  keyName: "do_k8s"
  # Path to private key file for this key
  privateKeyFile: "~/.ssh/do_k8s"
