#
# Create a volume and a network and bring up a virtual machine
# using KVM and libvirt
#
# To run this, you need the following installed on your machine:
# libvirt 
# python3-libvirt 
# lxml
# You can install all this on an Ubuntu system with 
# sudo apt-get install \
#  libvirt-daemon \
#  libvirt-clients \
#  virt-manager \
#  python3-libvirt
# pip3 install lxml
#
# Note that this creates a storage pool in the state subdirectory of the
# playbook dir, so make sure that you remove this storage pool before deleting
# the state directory to avoid dangling references
#
- name: Preparations
  hosts: localhost
  become: no 
  tasks:
    - name: Load variables
      include_vars:
        file: "{{playbook_dir}}/config.yaml"
    - name: Make sure that state directory exists
      file:
        path: "{{state_dir}}"
        state: directory
    - name: Make sure that we have downloaded the base image
      get_url:
        url: "{{base_image_url}}"
        dest: "{{base_image_path}}"
        checksum: "{{base_image_checksum}}"

- name: Create volume and network
  hosts: localhost
  become: no 
  roles:
    - libvirt_volume
    - libvirt_network

- name: Create virtual machine 
  hosts: localhost
  become: no
  roles:
    - libvirt_domain
